### ISSUE TITLE
Mobile Navigation Quick Bar not loading animation

### ISSUE THREAD

**Issue by Nischay-Pro** [Nischay-Pro/VM-Site-new#1]
Mobile Navigation Quick Bar is not working on all pages except the Index page.

![image](https://cloud.githubusercontent.com/assets/15060256/21957159/a0dfa416-dab6-11e6-822c-e6805b800b26.png)
![image](https://cloud.githubusercontent.com/assets/15060256/21957161/a845e184-dab6-11e6-9606-efa02e097fab.png)

Works on Index page

Doesn't work on other pages
![image](https://cloud.githubusercontent.com/assets/15060256/21957166/c9e7d748-dab6-11e6-8ebe-178ebf7823c6.png)

I believe the navigation depends on these 2 values
![image](https://cloud.githubusercontent.com/assets/15060256/21957168/d8caba64-dab6-11e6-88c8-3f609a356d7c.png)

Somewhere in the code
![image](https://cloud.githubusercontent.com/assets/15060256/21957173/ec73d3b6-dab6-11e6-8b90-eb3d609a3a72.png)

These two are responsible for the navigation bar to pop up in Mobile View

**Comment by aero31aero** [comment]
Needs lot of debugging. Failing to reproduce till now.
