### ISSUE TITLE
Sidebar Parent Menu Disappearing

### ISSUE THREAD

**Issue by Nischay-Pro** [Nischay-Pro/VM-Site-new#2]
When navigating using the sidebar, the parent menu is disappearing.

Issue affects both Mobile and Web.

**Comment by aero31aero** [comment]
I thought that weird menu view was intentional.

Post screenshot of expected functionality.

**Comment by Nischay-Pro** [comment]
Well don't have the screenshot but the user should be able to navigate to the parent menu and when clicked on parent menu should navigate
